apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  # type: ClusterIP // clusterIP is default no need to write 
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017